openapi: 3.0.0
info:
  title: Book Summary API
  version: 1.0.0
  description: API for managing book summaries and related questions.
servers:
  - url: https://api.example.com/v1

paths:
  /books/{book_id}:
    get:
      summary: Get a single book summary with questions
      parameters:
        - name: book_id
          in: path
          required: true
          description: The ID of the book to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  book:
                    type: object
                    properties:
                      title:
                        type: string
                      author:
                        type: string
                      link:
                        type: string
                      image:
                        type: string
                  question:
                    type: array
                    items:
                      type: object
                      properties:
                        question_id:
                          type: string
                        body:
                          type: string

  /books:
    get:
      summary: Get a list of books with summaries
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    book_id:
                      type: string
                    title:
                      type: string
                    author:
                      type: string
                    image:
                      type: string

  /books/{book_id}/summary:
    post:
      summary: Create a summary for a book
      parameters:
        - name: book_id
          in: path
          required: true
          description: The ID of the book to summarize
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      responses:
        '201':
          description: Summary created successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}

  /books/{book_id}/summary/{summary_id}:
    put:
      summary: Update a book summary
      parameters:
        - name: book_id
          in: path
          required: true
          description: The ID of the book
          schema:
            type: string
        - name: summary_id
          in: path
          required: true
          description: The ID of the summary to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      responses:
        '204':
          description: Summary updated successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}

    delete:
      summary: Delete a book summary
      parameters:
        - name: book_id
          in: path
          required: true
          description: The ID of the book
          schema:
            type: string
        - name: summary_id
          in: path
          required: true
          description: The ID of the summary to delete
          schema:
            type: string
      responses:
        '204':
          description: Summary deleted successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}

  /books/{book_id}/summary/{summary_id}/questions:
    get:
      summary: Get questions from a book summary
      parameters:
        - name: book_id
          in: path
          required: true
          description: The ID of the book
          schema:
            type: string
        - name: summary_id
          in: path
          required: true
          description: The ID of the summary
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  question_id:
                    type: string
                  body:
                    type: string

  /books/{book_id}/summary/{summary_id}/answer/{question_id}:
    post:
      summary: Submit an answer to a question
      parameters:
        - name: book_id
          in: path
          required: true
          description: The ID of the book
          schema:
            type: string
        - name: summary_id
          in: path
          required: true
          description: The ID of the summary
          schema:
            type: string
        - name: question_id
          in: path
          required: true
          description: The ID of the question
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question_id:
                  type: string
                user_answer:
                  type: string
      responses:
        '201':
          description: Answer submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
                  user_answer:
                    type: string
                  summary:
                    type: string
                  question:
                    type: string
