[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
registry.workspace = true
axum.workspace = true
shared.workspace = true
kernel.workspace = true
axum-extra.workspace = true
serde.workspace = true